apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: agent1
  name: agent2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agent2
  template:
    metadata:
      labels:
        app: agent2
    spec:
      containers:
        - name: container
          image: icr.io/ibm/satellite-connector/satellite-connector-agent:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: connector-agent-secrets
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

