# Use UBI-based Helm Operator from Red Hat (must be logged in to registry.redhat.io)
FROM registry.redhat.io/openshift4/ose-helm-operator:v4.14

# Copy your Helm chart to the default expected directory
COPY Operator/ /helm-charts/

