- name: Playbook to install Satellite Connector agent
  hosts: all
  become: True
  vars_prompt:
      name: apikey
      prompt: Please insert API Key generated for Satellite agent Connector
      private: True
  tasks:
   - name: Update all packages
     shell: dnf update -y
   - name: Install podman and network tools
     dnf:
         name: podman,bind-utils,net-tools,nmap-ncat
         state: present
   - name: Set podman to private CR
     shell: podman login -u iamapikey -p {{apikey}} private.icr.io
   - name: Pull Satellite agent image
     shell: podman pull private.icr.io/ibm/satellite-connector/satellite-connector-agent:latest
   - name: Create folder
     file: 
        path: /opt/satellite/agent/env-files
        recurse: True
        state: directory
        mode: '0750'
   - name: Generate env file from template
     blockinfile:
       create: True
       path: /opt/satellite/agent/env-files/env.txt
       mode: '0644'
       block: |
        SATELLITE_CONNECTOR_ID={{satellite_connector_id}}
        SATELLITE_CONNECTOR_IAM_APIKEY=/agent-env-files/apikey
        SATELLITE_CONNECTOR_DIRECT_LINK_INGRESS=d-01-ws.private.{{satellite_region}}.link.satellite.cloud.ibm.com
        LOG_LEVEL=info
        SATELLITE_CONNECTOR_TAGS={{ansible_hostname}}
      
   - name: Generate apikey file
     shell: echo {{apikey}} > /opt/satellite/agent/env-files/apikey
   - name: Copy satellite-agent service to /usr/lib/systemd/system
     blockinfile:
       create: True
       path: /etc/systemd/system/satellite-connector-agent.service
       block: |
         # autogenerated by Podman 5.4.0
         # Wed Jul 30 04:15:45 UTC 2025
         
         [Unit]
         Description=Podman container-Satellite Connector Agent
         Documentation=man:podman-generate-systemd(1)
         Wants=network-online.target
         After=network-online.target
         RequiresMountsFor=%t/containers
         
         [Service]
         Environment=PODMAN_SYSTEMD_UNIT=%n
         Restart=on-failure
         TimeoutStopSec=70
         ExecStart=/usr/bin/podman run \
         	--cidfile=%t/%n.ctr-id \
         	--cgroups=no-conmon \
         	--rm \
         	--sdnotify=conmon \
         	-d \
         	--env-file /opt/satellite/agent/env-files/env.txt \
         	-v /opt/satellite/agent/env-files:/agent-env-files private.icr.io/ibm/satellite-connector/satellite-connector-agent \
         	--name satellite-connector-agent
         ExecStop=/usr/bin/podman stop \
         	--ignore -t 10 \
         	--cidfile=%t/%n.ctr-id
         ExecStopPost=/usr/bin/podman rm \
         	-f \
         	--ignore -t 10 \
         	--cidfile=%t/%n.ctr-id
         Type=notify
         NotifyAccess=all
         
         [Install]
         WantedBy=default.target
   - name: Start service
     systemd_service: 
        daemon_reload: True
        name: satellite-connector-agent
        state: restarted
        enabled: True
